#test
#Tue May 10 10:42:33 CST 2011

file_size_threshold=10000000
app_use_sso=true
password_key=vnetoo
file_upload_max_size=1000000000

product_debug=false
servlet_encoding=UTF-8
#\u5DE5\u7A0B\u7684\u6807\u9898
product_title=考试系统
log4j_config_file=/WEB-INF/classes/log4j.xml
checkValidateCode = false
student_role_id = 3

#web_root=http://home.vnetoo.com:8054/examination
web_root=http://localhost/examination

paper_dir=paper
student_auth=examPaper!goExam.action,examPaper!goContinueExam.action,examPaper!saveExamResult.action,examPaper!saveFinalExamResult.action,examPaper!showExamResult.action,paperTest!search.action,paperTest!query.action,login!frame.action,examPaper!getStudentAnswerStatus.action,examPaper!getRemainTime.action

integrated_running=false

valid_student_url=http://localhost/examtest/tests/validStudentPermission
fetch_student_info_url=http://localhost/examtest/tests/fetchStudentInfo
init_password=000000