
CREATE TABLE EXAM.APP_SCOPE_USER_REL
(
  USER_ID  NUMBER(19)                           NOT NULL,
  SCOPE_ID  NUMBER(19)                           NOT NULL
)
TABLESPACE USERS
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           );

-- 
-- Non Foreign Key Constraints for Table SYS_USER_ROLE_REL 
-- 
ALTER TABLE EXAM.APP_SCOPE_USER_REL ADD (
  CONSTRAINT PK_APP_SCOPE_USER_REL
  PRIMARY KEY
  (USER_ID,SCOPE_ID)
  ENABLE VALIDATE);

-- 
-- Foreign Key Constraints for Table SYS_USER_ROLE_REL 
-- 
ALTER TABLE EXAM.APP_SCOPE_USER_REL ADD (
  CONSTRAINT APP_SCOPE_USER_REL_R01 
  FOREIGN KEY (USER_ID) 
  REFERENCES EXAM.SYS_USER (ID)
  ENABLE VALIDATE);

ALTER TABLE EXAM.APP_SCOPE_USER_REL ADD (
  CONSTRAINT APP_SCOPE_USER_REL_R02 
  FOREIGN KEY (SCOPE_ID) 
  REFERENCES EXAM.APP_SCOPE (ID)
  ENABLE VALIDATE);
  
ALTER TABLE EXAM_STUDENT_ANSWER ADD REVIEW_STATUS NUMBER(1);
ALTER TABLE EXAM_STUDENT_ANSWER_DETAIL ADD REVIEWER_ID NUMBER(19);
ALTER TABLE EXAM_STUDENT_ANSWER_DETAIL ADD REVIEW_DATE DATE;
COMMENT ON COLUMN EXAM_STUDENT_ANSWER.REVIEW_STATUS IS '�ľ�״̬';
COMMENT ON COLUMN EXAM_STUDENT_ANSWER_DETAIL.REVIEWER_ID IS '�ľ���ID';
COMMENT ON COLUMN EXAM_STUDENT_ANSWER_DETAIL.REVIEW_DATE  IS '�ľ�����';

/*�޸�֪ʶ��״̬���*/
alter table EXAM_KEY_POINT rename ststus TO status;

ALTER TABLE APP_SCOPE ADD STATUS NUMBER(1) NOT NULL;
ALTER TABLE EXAM_STUDENT_ANSWER ADD BUSINESS_INFO VARCHAR2(4000);